[DOCUMENTATION]
ORG_NAME="XLMCOIN"
ORG_URL="https://xlmcoin.github.io"
ORG_SUPPORT_EMAIL="parsunnetwork@gmail.com"
ORG_DESCRIPTION="Stellar Network Assets Platform"
ORG_LOGO = "https://xlmcoin.github.io/favicon.ico"

[[CURRENCIES]]
code=""
name=""
issuer=""
desc=""
image=""
conditions=""
display_decimals=7
is_asset_anchored=false
